#!/bin/bash

if [ "$EUID" -eq 0 ]
    then echo "Cannot be root!"
    exit 1
fi

BASE_DIR=$(realpath "$(dirname $0)")
INTERFACES_BASE_DIR=$1

if [ -z ${INTERFACES_BASE_DIR} ]; then
    SRC_ROS_MSG_DIR=~/tj2_ros/src/tj2_interfaces/msg
    SRC_ROS_SRV_DIR=~/tj2_ros/src/tj2_interfaces/srv
else
    SRC_ROS_MSG_DIR=${INTERFACES_BASE_DIR}/msg
    SRC_ROS_SRV_DIR=${INTERFACES_BASE_DIR}/srv
fi

ROS_MSG_DEP_DIR=${BASE_DIR}/../genmsg

ROS_MSG_DIR=${BASE_DIR}/../genmsg/tj2_interfaces/msg
ROS_SRV_DIR=${BASE_DIR}/../genmsg/tj2_interfaces/srv

mkdir -p ${ROS_MSG_DIR}
mkdir -p ${ROS_SRV_DIR}

rm ${ROS_MSG_DIR}/*
rm ${ROS_SRV_DIR}/*

cp ${SRC_ROS_MSG_DIR}/* ${ROS_MSG_DIR}
cp ${SRC_ROS_SRV_DIR}/* ${ROS_SRV_DIR}

if [ ! -d ${ROS_MSG_DEP_DIR}/std_msgs ] ; then
    git clone https://github.com/ros/std_msgs.git ${ROS_MSG_DEP_DIR}/std_msgs
fi

if [ ! -d ${ROS_MSG_DEP_DIR}/common_msgs ] ; then
    git clone https://github.com/ros/common_msgs.git ${ROS_MSG_DEP_DIR}/common_msgs
fi

if [ ! -d ${ROS_MSG_DEP_DIR}/vision_msgs ] ; then
    git clone https://github.com/ros-perception/vision_msgs.git -b noetic-devel ${ROS_MSG_DEP_DIR}/vision_msgs
fi

GEN_ROS_MSG_DIR=/home/tj2/genmsg

${BASE_DIR}/run-in-container rospy-build genmsg ${GEN_ROS_MSG_DIR}/tj2_interfaces -s ${GEN_ROS_MSG_DIR}
${BASE_DIR}/run-in-container pip install -e ${GEN_ROS_MSG_DIR}/tj2_interfaces --quiet && \
${BASE_DIR}/run-in-container rm -r /home/tj2/src/tj2_interfaces
${BASE_DIR}/run-in-container mv ${GEN_ROS_MSG_DIR}/tj2_interfaces/tj2_interfaces /home/tj2/src

${BASE_DIR}/run-in-container rospy-build genmsg ${GEN_ROS_MSG_DIR}/vision_msgs -s ${GEN_ROS_MSG_DIR}
${BASE_DIR}/run-in-container pip install -e ${GEN_ROS_MSG_DIR}/vision_msgs --quiet && \
${BASE_DIR}/run-in-container rm -r /home/tj2/src/vision_msgs
${BASE_DIR}/run-in-container mv ${GEN_ROS_MSG_DIR}/vision_msgs/vision_msgs /home/tj2/src
