#!/bin/bash

BASE_DIR=$(realpath "$(dirname $0)")

cd ${BASE_DIR}/..
docker run --rm \
    --name run_diffyjr_rospy \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v src:/home/tj2/src:rw \
    diffyjr_rospy:latest \
    $@
