#!/bin/bash

BASE_DIR=$(realpath "$(dirname $0)")

docker run -it --rm \
    --name run_diffyjr_rospy \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v ${BASE_DIR}/install:/home/tj2/install:rw \
    -v ${BASE_DIR}/../src:/home/tj2/src:rw \
    diffyjr_rospy:latest \
    $@
