version: "3"

services:
  diffyjr_rospy_devcontainer:
    image: diffyjr_rospy:latest
    container_name: diffyjr_rospy_devcontainer
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    volumes:
      - /home/${USER}/diffyjr_rospy:/home/tj2/diffyjr_rospy:rw
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "sleep infinity"
